using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Qengu.GodotUtils.SourceGenerators;

/// <summary>
/// A source generator which generates a statically typed Instantiate method, which allows arguments
/// to be passed in on instantiate 
/// </summary>
[Generator]
sealed public class InstantiableSourceGenerator : IIncrementalGenerator
{

    private const string ATTRIBUTENAME = "Qengu.GodotUtils.GeneratorAnnotations.InstantiableAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {

        IncrementalValuesProvider<InstantiableInfo?> instantiableInfo =
            context.SyntaxProvider
            .ForAttributeWithMetadataName(
                    ATTRIBUTENAME,
                    predicate: static (s, _) => true,
                    transform: static (ctx, _) => GetInstantiableInfo(ctx))
            .Where(static m => m is not null);

        var combined = instantiableInfo.Combine(GeneratorHelper.Godot.GetProjectDirectory(context));

        context.RegisterSourceOutput(combined, static (spc, src) => Execute(src.Left, src.Right, spc));
    }

    private static InstantiableInfo? GetInstantiableInfo(GeneratorAttributeSyntaxContext ctx)
    {
        var symbol = (INamedTypeSymbol)ctx.TargetSymbol;
        var classDeclaration = (ClassDeclarationSyntax)ctx.TargetNode;

        AttributeData data = ctx.Attributes.First();
        string initFuncName = (string)data.ConstructorArguments[0].Value!;
        string? sceneName = (string?)data.ConstructorArguments[1].Value!;

        return new InstantiableInfo(
                symbol.ContainingNamespace.IsGlobalNamespace ? null : symbol.ContainingNamespace.ToDisplayString(),
                symbol.Name,
                sceneName,
                initFuncName,
                GeneratorHelper.GetMethodArguments(classDeclaration, initFuncName),
                ctx.TargetNode.SyntaxTree.FilePath);
    }

    private static void Execute(InstantiableInfo? info, string? projectDir, SourceProductionContext spc)
    {
        if (string.IsNullOrEmpty(projectDir)) return;
        if (info is not { } value) return;

        string resPath = ToResPath(info.AbsFilePath, projectDir!, info.SceneName);

        bool hasInit = value.InitParams != null;

        var paramsDefinitionText = hasInit ? string.Join(", ",
                value.InitParams.Select(param => param.FullArgument)) : "";

        var sb = new StringBuilder()
            .AppendLine("using Godot;")
            .AppendLine()
            .AppendLine("// <auto-generated>")
            .AppendFormat("// Source: {0}", resPath)
            .AppendLine();

        if (value.NamespaceName != null) { sb.AppendFormat("namespace {0};", value.NamespaceName).AppendLine(); }

        sb
        .AppendFormat("public partial class {0}", value.ClassName)
        .AppendLine()
        .AppendLine("{")
        .AppendLine()
        .AppendFormat("\tprivate static PackedScene _scene = GD.Load<PackedScene>(\"{0}\");", resPath)
        .AppendLine()
        .AppendLine()
        .AppendFormat("\tpublic static {0} Instantiate({1})", value.ClassName, paramsDefinitionText)
        .AppendLine()
        .AppendLine("\t{")
        .AppendLine()
        .AppendFormat("\t\t{0} scene = _scene.Instantiate<{0}>();", value.ClassName)
        .AppendLine();

        if (hasInit)
        {
            var argumentsText = string.Join(", ",
                    value.InitParams.Select(param => string.Format("{0}", param.Name)));
            sb.AppendFormat("\t\tscene.{0}({1});", value.InitName, argumentsText);
        }

        sb
        .AppendLine()
        .AppendLine("\t\treturn scene;")
        .AppendLine("\t}")
        .AppendLine()
        .AppendLine("}");

        var output = sb.ToString();
        spc.AddSource($"{value.ClassName}.g.cs", SourceText.From(output, Encoding.UTF8));
    }

    private static string ToResPath(string absPath, string projectDir, string? customFileName = null)
    {
        string normalizedRoot = projectDir.Replace('\\', '/').TrimEnd('/');
        string normalizedFile = absPath.Replace('\\', '/');

        if (!normalizedFile.StartsWith(normalizedRoot, StringComparison.OrdinalIgnoreCase)) return normalizedFile;

        string relative = normalizedFile.Substring(normalizedRoot.Length).TrimStart('/');
        string dir = Path.GetDirectoryName(relative);

        string fileName = Path.GetFileNameWithoutExtension(relative);
        if (customFileName != null)
            fileName = customFileName;
        return "res://" + Path.Combine(dir, StringUtilities.ToSnakeCase(fileName) + ".tscn");
    }

    sealed private record InstantiableInfo
    {
        public readonly string? NamespaceName;
        public readonly string ClassName;
        public readonly string? SceneName;
        public readonly ArgumentData[]? InitParams;
        public readonly string AbsFilePath;

        public readonly string InitName;
        public InstantiableInfo(string? namespaceName, string className, string? sceneName, string initName, ArgumentData[]? _initParams, string absFilePath)
        {
            NamespaceName = namespaceName;
            ClassName = className;
            SceneName = sceneName;
            InitName = initName;
            InitParams = _initParams;
            AbsFilePath = absFilePath;
        }
    }

}
